function resultTable = initIMUTable()
%INITIMUTABLE Init empty table for results

    name_type = [["Time", "datetime"];...
                 ["GyroX", "double"];...
                 ["GyroY", "double"];...
                 ["GyroZ", "double"];...
                 ["AccX", "double"];...
                 ["AccY", "double"];...
                 ["AccZ", "double"];...
                 ["Q_w", "double"];...
                 ["Q_i", "double"];...
                 ["Q_j", "double"];...
                 ["Q_k", "double"]];
    
    resultTable = table('Size',[0 size(name_type, 1)],...
                    'VariableNames', name_type(:,1),...
                    'VariableTypes', name_type(:,2));

end

