function statTable = initStatTable()
%INITSTATTABLE Init empty table for run statistics

    name_type = [["Label", "string"];...
                 ["Mode", "string"];...
                 ["Speed", "double"];...
                 ["x_MSE", "double"];...
                 ["y_MSE", "double"];...
                 ["vZ_MSE", "double"];...
                 ["x_MAD", "double"];...
                 ["y_MAD", "double"];...
                 ["vZ_MAD", "double"];...
                 ["x_MAE", "double"];...
                 ["y_MAE", "double"];...
                 ["vZ_MAE", "double"];...
                 ["x_m", "double"];...
                 ["x_std", "double"];...
                 ["y_m", "double"];...
                 ["y_std", "double"];...
                 ["vZ_m", "double"];...
                 ["vZ_std", "double"];...
                 ["dx_MSE", "double"];...
                 ["dy_MSE", "double"];...
                 ["dx_MAD", "double"];...
                 ["dy_MAD", "double"];...
                 ["dx_MAE", "double"];...
                 ["dy_MAE", "double"];...
                 ["dx_m", "double"];...
                 ["dx_std", "double"];...
                 ["dy_m", "double"];...
                 ["dy_std", "double"]];
    
    statTable = table('Size',[0 size(name_type, 1)],...
                    'VariableNames', name_type(:,1),...
                    'VariableTypes', name_type(:,2));
end

