function resultTable = initGhTable()

    name_type = [["Time", "datetime"];...
                 ["angleX", "double"];...
                 ["angleY", "double"];...
                 ["accZ", "double"];...
                 ["PID_X", "double"];...
                 ["PID_Y", "double"];...
                 ["uFL", "double"];...
                 ["uFR", "double"];...
                 ["uBL", "double"];...
                 ["uBR", "double"]];
    
    resultTable = table('Size',[0 size(name_type, 1)],...
                    'VariableNames', name_type(:,1),...
                    'VariableTypes', name_type(:,2));
end

